config/routes.rb
Rails.application.routes.draw do
  resources :profile_requests

  devise_for :admins

  resources :tracks
  resources :courses

  get 'static_pages/home'
  get 'static_pages/help'

  root 'static_pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/profile_request.rb
class ProfileRequest < ActiveRecord::Base
end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/models/track_course.rb
class TrackCourse < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all.order('lower(course_name) collate "C"')
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        AdminMailer.course_added_email(@course).deliver

        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        AdminMailer.course_updated_email(@course).deliver

        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_name, :stage_count)
    end
end

app/controllers/profile_requests_controller.rb
class ProfileRequestsController < ApplicationController
  before_action :set_profile_request, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @profile_requests = ProfileRequest.all
    respond_with(@profile_requests)
  end

  def show
    respond_with(@profile_request)
  end

  def new
    @profile_request = ProfileRequest.new
    respond_with(@profile_request)
  end

  def edit
  end

  def create
    @profile_request = ProfileRequest.new(profile_request_params)
    @profile_request.save
    respond_with(@profile_request)
  end

  def update
    @profile_request.update(profile_request_params)
    respond_with(@profile_request)
  end

  def destroy
    @profile_request.destroy
    respond_with(@profile_request)
  end

  private
    def set_profile_request
      @profile_request = ProfileRequest.find(params[:id])
    end

    def profile_request_params
      params.require(:profile_request).permit(:profile_id, :request_date, :badges_finished, :total_points, :courses_started, :courses_finished, :tracks_started, :tracks_finished, :points_json, :process_notes)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all.order(:track_name)
    @track_courses = TrackCourse.all.order(:track_name, :course_order)
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:track_name, :course_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return the bootstrap class for the flash
	def bootstrap_class_for flash_type
	    case flash_type
	      when :success, "success"
	        "alert-success"
	      when :error, "error"
	        "alert-danger"
	      when :alert, "alert"
	        "alert-warning"
	      else
	        "alert-info"
	    end
	end
		
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/profile_requests_helper.rb
module ProfileRequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :course_name %><br>
    <%= f.text_field :course_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :stage_count %><br>
    <%= f.number_field :stage_count, class: "form-control" %>
  </div>
  <%= f.submit class: "btn" %>
<% end %>

app/views/courses/edit.html.erb
<div class="row">
	<div class="col-md-4 col-lg-4 col-md-offset-3 col-lg-offset-3">
		<h1>Editing Course</h1>

		<%= render 'form' %>
		<br>
		<%= link_to courses_path, class: "btn btn-default" do %>
		<span class="glyphicon glyphicon-arrow-left"></span>
		<% end %>
	</div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="page-header">
      <h1><span class="glyphicon glyphicon-book"></span> Courses</h1>
    </div>

    <table class="table table-condensed" >
      <thead>
        <tr>
          <th>Course Name</th>
          <th class="text-center">Stages</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @courses.each do |course| %>
          <tr>
            <td><%= link_to course.course_name, edit_course_path(course) %></td>
            <td class="text-center"><%= course.stage_count %></td>
            <td><%= link_to course, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to new_course_path do %>
    <span class="badge"><span class="glyphicon glyphicon-plus"></span></span> New Course
    <% end %>
    <br><br>
  </div>
</div>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course name:</strong>
  <%= @course.course_name %>
</p>

<p>
  <strong>Stage count:</strong>
  <%= @course.stage_count %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Transcript</a>
        </div>
		<form class="navbar-form navbar-left" role="treehouse-profile">
        	<div class="form-group">
          		<input id="profile-url" type="text" class="form-control" value="gaylenmiller2" placeholder="Treehouse Profile">
        	</div>
        	<span type="submit" class="btn btn-success" id="generate-button">Generate</span>
		</form>        
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="<%= tracks_path %>">Tracks</a></li>
            <li><a href="<%= courses_path %>">Courses</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transcript</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
	<%#= render 'layouts/menu' %>
	<%= render 'layouts/flash_messages' %>

	<div class="container">
		<div class="row" >

			<div class="col-md-4 col-lg-3">
				<%= link_to static_pages_home_path do %>
					<%= image_tag "certificate-icon-aqua.png", {class: "img-responsive"} %>
				<% end %>
			</div>
			
			<div class="col-md-6 col-lg-8">
				<h1>Transcript Generator</h1>
				<h4>Treehouse Profile ID</h4>
	        	<div class="form-group">
          		<input id="profile-url" type="text" class="form-control" value="gaylenmiller2" placeholder="Treehouse Profile">
	        	</div>
   	     	<span type="submit" class="btn btn-success" id="generate-button">Generate</span>
			</div>

			<div class="col-md-2 col-lg-1">
				
				<%= link_to static_pages_help_path do %>
					<h2 data-toggle="tooltip" data-placement="left" title="Help"><span class="glyphicon glyphicon-question-sign"></span></h2>
				<% end %>
				<%= link_to courses_path do %>
					<h2 data-toggle="tooltip" data-placement="left" title="Courses"><span class="glyphicon glyphicon-book"></span></h2>
				<% end %>
				<%= link_to tracks_path do %>
					<h2 data-toggle="tooltip" data-placement="left" title="Tracks"><span class="glyphicon glyphicon-list"></span></h2>
				<% end %>
				<% if admin_signed_in? %>
					<%= link_to destroy_admin_session_path, {method: 'delete'} do %>
						<h2 data-toggle="tooltip" data-placement="left" title="Admin Sign Out"><span class="glyphicon glyphicon-log-out"></span></h2>
					<% end %>
				<% else %>
					<%= link_to new_admin_session_path do %>
						<h2 data-toggle="tooltip" data-placement="left" title="Admin Sign In"><span class="glyphicon glyphicon-log-in"></span></h2>
					<% end %>
				<% end %>
			</div>
		</div>

		<%= yield %>
	</div> <!-- /container -->
</body>
</html>

app/views/profile_requests/_form.html.erb
<%= form_for(@profile_request) do |f| %>
  <% if @profile_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile_request.errors.count, "error") %> prohibited this profile_request from being saved:</h2>

      <ul>
      <% @profile_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>
  <div class="field">
    <%= f.label :request_date %><br>
    <%= f.date_select :request_date %>
  </div>
  <div class="field">
    <%= f.label :badges_finished %><br>
    <%= f.number_field :badges_finished %>
  </div>
  <div class="field">
    <%= f.label :total_points %><br>
    <%= f.number_field :total_points %>
  </div>
  <div class="field">
    <%= f.label :courses_started %><br>
    <%= f.number_field :courses_started %>
  </div>
  <div class="field">
    <%= f.label :courses_finished %><br>
    <%= f.number_field :courses_finished %>
  </div>
  <div class="field">
    <%= f.label :tracks_started %><br>
    <%= f.number_field :tracks_started %>
  </div>
  <div class="field">
    <%= f.label :tracks_finished %><br>
    <%= f.number_field :tracks_finished %>
  </div>
  <div class="field">
    <%= f.label :points_json %><br>
    <%= f.text_field :points_json %>
  </div>
  <div class="field">
    <%= f.label :process_notes %><br>
    <%= f.text_field :process_notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profile_requests/edit.html.erb
<h1>Editing profile_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile_request %> |
<%= link_to 'Back', profile_requests_path %>

app/views/profile_requests/index.html.erb
<h1>Listing profile_requests</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Request date</th>
      <th>Badges finished</th>
      <th>Total points</th>
      <th>Courses started</th>
      <th>Courses finished</th>
      <th>Tracks started</th>
      <th>Tracks finished</th>
      <th>Points json</th>
      <th>Process notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profile_requests.each do |profile_request| %>
      <tr>
        <td><%= profile_request.profile_id %></td>
        <td><%= profile_request.request_date %></td>
        <td><%= profile_request.badges_finished %></td>
        <td><%= profile_request.total_points %></td>
        <td><%= profile_request.courses_started %></td>
        <td><%= profile_request.courses_finished %></td>
        <td><%= profile_request.tracks_started %></td>
        <td><%= profile_request.tracks_finished %></td>
        <td><%= profile_request.points_json %></td>
        <td><%= profile_request.process_notes %></td>
        <td><%= link_to 'Show', profile_request %></td>
        <td><%= link_to 'Edit', edit_profile_request_path(profile_request) %></td>
        <td><%= link_to 'Destroy', profile_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile request', new_profile_request_path %>

app/views/profile_requests/new.html.erb
<h1>New profile_request</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_requests_path %>

app/views/profile_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @profile_request.profile_id %>
</p>

<p>
  <strong>Request date:</strong>
  <%= @profile_request.request_date %>
</p>

<p>
  <strong>Badges finished:</strong>
  <%= @profile_request.badges_finished %>
</p>

<p>
  <strong>Total points:</strong>
  <%= @profile_request.total_points %>
</p>

<p>
  <strong>Courses started:</strong>
  <%= @profile_request.courses_started %>
</p>

<p>
  <strong>Courses finished:</strong>
  <%= @profile_request.courses_finished %>
</p>

<p>
  <strong>Tracks started:</strong>
  <%= @profile_request.tracks_started %>
</p>

<p>
  <strong>Tracks finished:</strong>
  <%= @profile_request.tracks_finished %>
</p>

<p>
  <strong>Points json:</strong>
  <%= @profile_request.points_json %>
</p>

<p>
  <strong>Process notes:</strong>
  <%= @profile_request.process_notes %>
</p>

<%= link_to 'Edit', edit_profile_request_path(@profile_request) %> |
<%= link_to 'Back', profile_requests_path %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

<div class="form-group">
	<label for="course-name">Course Name</label>
	<input id="course-name" type="text" class="form-control" placeholder="Course Name">
	
</div>
<span class="btn btn-success" id="add-course-button">Add Course</span>

app/views/static_pages/home.html.erb
<div class="row" id="badges-info">
	<div class="col-md-10 col-lg-10 col-md-offset-1 col-lg-offset-1">

		<div class="page-header">
			<h2 id="profile-header-name">Lorem Ipsum</h2>
				<h4>Transcript</h4>
		</div>
		<h3>Tracks</h3>
		<div id="tracks-div"></div>
		<h3>Courses</h3>
		<div id="courses-div"></div>
		<h3>Badges</h3>
		<div id="badges-div"></div>
	</div>	
</div>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :track_name %><br>
    <%= f.text_field :track_name %>
  </div>
  <div class="field">
    <%= f.label :course_count %><br>
    <%= f.number_field :course_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1 class="page-header">Tracks and Track Courses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Track name</th>
      <th>Course count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.track_name %></td>
        <td><%= track.course_count %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th>Course Name</th>
      <th>Track Name</th>
      <th>Course Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @track_courses.each do |track_course| %>
      <tr>
        <td><%= track_course.course_name %></td>
        <td><%= track_course.track_name %></td>
        <td><%= track_course.course_order %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Track name:</strong>
  <%= @track.track_name %>
</p>

<p>
  <strong>Course count:</strong>
  <%= @track.course_count %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>